import type { EditorialCard, GameDefinition } from "../games/types";

export const games: GameDefinition[] = [
  {
    id: "fuori-traccia",
    number: 1,
    title: "Labirinto matto",
    shortTitle: "Fuori traccia",
    category: "percorso",
    intro: "Una strada è prevista. L’altra compare quando smetti di obbedire al disegno.",
    action: "GIOCA",
    component: () => import("../games/desire-path/Game"),
    conclusion: "Una scorciatoia individuale diventa infrastruttura quando abbastanza persone la ripetono.",
    sources: [
      { label: "X — Project Retweet: Phase One", href: "https://blog.x.com/en_us/a/2009/project-retweet-phase-one" },
      { label: "X — The hashtag at 10 years young", href: "https://blog.x.com/en_us/topics/product/2017/the-hashtag-at-ten-years-young" },
    ],
  },
  {
    id: "intruso",
    number: 2,
    title: "Trova l’intruso",
    shortTitle: "Tracce contraddittorie",
    category: "osservazione",
    intro: "Tutti dichiarano qualcosa con il corpo. Uno, però, viene smentito da ciò che ha lasciato.",
    action: "OSSERVA",
    component: () => import("../games/odd-one-out/Game"),
    conclusion: "Le tracce aiutano a inferire un passaggio. Anche un indizio corretto può raccontare la storia sbagliata.",
  },
  {
    id: "cassetto",
    number: 3,
    title: "Il cassetto disordinato",
    shortTitle: "Stratigrafia domestica",
    category: "mistero",
    intro: "Sposta il presente. Sotto, il cassetto conserva oggetti che nessuno ha deciso di archiviare.",
    action: "CERCA",
    component: () => import("../games/junk-drawer/Game"),
    conclusion: "L’ordine di un cassetto è temporaneo. La sua profondità, invece, fa da calendario.",
  },
  {
    id: "collega-punti",
    number: 4,
    title: "Collega i punti",
    shortTitle: "Gesto ripetuto",
    category: "percorso",
    intro: "Segui i numeri. La tua linea resta imperfetta; le successive la renderanno riconoscibile.",
    action: "TRACCIA",
    component: () => import("../games/connect-dots/Game"),
    conclusion: "Una linea devia. Cento linee simili diventano un’impronta.",
  },
  {
    id: "polvere",
    number: 5,
    title: "Lascia un segno",
    shortTitle: "Polvere e scelta",
    category: "percorso",
    intro: "Pulisci tutto, oppure usa la polvere come superficie. Sei tu a decidere che cosa resta.",
    action: "DISEGNA",
    component: () => import("../games/dust-canvas/Game"),
    conclusion: "Cancellare e scrivere possono essere lo stesso gesto, visto dai due lati della polvere.",
  },
  {
    id: "prima-dopo",
    number: 6,
    title: "Prima / Dopo",
    shortTitle: "Il passaggio",
    category: "osservazione",
    intro: "Sette piccoli cambiamenti raccontano che qualcuno è passato. Trovali senza inventare il colpevole.",
    action: "CONFRONTA",
    component: () => import("../games/spot-difference/Game"),
    conclusion: "Una stanza registra soprattutto le azioni interrotte: una tazza, una sedia, un cassetto.",
  },
  {
    id: "caso-piatti",
    number: 7,
    title: "Il caso dei piatti",
    shortTitle: "Chi non ha lavato?",
    category: "mistero",
    intro: "Tre coinquilini. Cinque indizi. Una padella che nessuno ricorda di aver usato.",
    action: "INDAGA",
    component: () => import("../games/dish-mystery/Game"),
    conclusion: "La convivenza produce archivi involontari. Quasi tutti sono nel lavello.",
  },
  {
    id: "cinque-tracce",
    number: 8,
    title: "Cinque tracce",
    shortTitle: "Parola del giorno",
    category: "parole",
    intro: "Sei tentativi per una parola di cinque lettere legata a residui, gesti e usura.",
    action: "SCRIVI",
    component: () => import("../games/five-letters/Game"),
    conclusion: "Le parole sopravvivono anche come abitudini: un ordine di lettere ripetuto senza pensarci.",
  },
  {
    id: "cruciverba",
    number: 9,
    title: "Parole incrociate",
    shortTitle: "Otto definizioni",
    category: "parole",
    intro: "Un solo cruciverba compatto. Le definizioni vengono dalla vita ordinaria del volume.",
    action: "COMPILA",
    component: () => import("../games/crossword/Game"),
    conclusion: "Incrociare parole significa costringerle a condividere una lettera e, per un istante, un significato.",
  },
  {
    id: "scontrino",
    number: 10,
    title: "Scontrino umano",
    shortTitle: "Inventario involontario",
    category: "parole",
    intro: "Sei gesti quotidiani diventano un ritratto editoriale. Nessuna diagnosi, solo contabilità domestica.",
    action: "RISPONDI",
    component: () => import("../games/receipt-quiz/Game"),
    conclusion: "Un inventario non spiega una persona. Mostra però quante volte ha appoggiato le chiavi nello stesso punto.",
  },
  {
    id: "fondo-tazza",
    number: 11,
    title: "Fondo di tazza",
    shortTitle: "Residui in lettura",
    category: "rituale",
    intro: "Una lettura automatica e ludica dei residui. L’immagine resta sul tuo dispositivo.",
    action: "LEGGI",
    component: () => import("../games/coffee-reader/Game"),
    conclusion: "Il fondo non prevede il futuro. È già abbastanza occupato a registrare l’ultimo caffè.",
  },
  {
    id: "piede",
    number: 12,
    title: "Il piede sa",
    shortTitle: "Suola e usura",
    category: "rituale",
    intro: "Inquadra una suola o usa la demo. L’analisi resta locale e non formula diagnosi.",
    action: "OSSERVA",
    component: () => import("../games/foot-reader/Game"),
    conclusion: "Una suola non rivela chi sei. Rivela, al massimo, come ha incontrato il pavimento.",
  },
];

export const editorialCards: EditorialCard[] = [
  {
    id: "vignetta-1",
    type: "vignetta",
    title: "Oggetti smarriti",
    body: "Una chiave incontra una serratura che non ricorda più.",
    action: "GUARDA",
  },
  {
    id: "nota-redazione",
    type: "nota",
    title: "Nota di redazione",
    body: "Questo numero cerca le persone senza mostrarle: attraverso impronte, residui, pieghe e cattive abitudini.",
    action: "LEGGI",
  },
  {
    id: "archivio-minimo",
    type: "archivio",
    title: "Archivio minimo",
    body: "Alone di tazza · gradino consumato · sedia spostata · piega nel libro · tasto lucido.",
    action: "SFOGLIA",
  },
  {
    id: "vignetta-2",
    type: "vignetta",
    title: "Presenza assente",
    body: "La sedia è vuota. Il cuscino, meno.",
    action: "GUARDA",
  },
  {
    id: "bacheca",
    type: "bacheca",
    title: "Bacheca",
    body: "Classifiche locali dei giochi confrontabili e disegni in attesa di una futura moderazione.",
    action: "APRI",
  },
];
