const baseUrl = import.meta.env?.BASE_URL ?? '/vol1-test/';

export const jannelTarotCards = Object.freeze([
  { slug: 'il-nuovo-inquilino', roman: '0', title: 'Il nuovo inquilino', image: 'il-nuovo-inquilino.png', reading: 'Qualcosa ricomincia da zero. Non sai ancora dove sono i contatori, quale bidone usare o chi evitare sulle scale. Per una volta, non saperlo è un vantaggio: puoi ancora decidere che vicino diventare.' },
  { slug: 'il-corriere', roman: 'I', title: 'Il corriere', image: 'il-corriere.png', reading: 'Qualcosa è in arrivo. Potrebbe essere importante, potrebbe essere un pacco lasciato a un vicino che non conosci. In ogni caso, oggi qualcuno busserà metaforicamente alla tua porta. Conviene aprire.' },
  { slug: 'la-pettegola', roman: 'II', title: 'La pettegola', image: 'la-pettegola.png', reading: 'Una notizia farà più piani dell’ascensore. Prima di sera sarà passata attraverso abbastanza persone da non assomigliare più all’originale. Ascolta pure, ma lascia almeno una porta chiusa tra te e la versione definitiva.' },
  { slug: 'la-vecchia', roman: 'III', title: 'La vecchia', image: 'la-vecchia.png', reading: 'Quello che ti sembra nuovo, probabilmente è già successo nel 1997. Oggi presta attenzione a chi guarda dalla stessa finestra da abbastanza tempo da sapere come vanno certe cose.' },
  { slug: 'l-amministratore', roman: 'IV', title: 'L’amministratore', image: 'l-amministratore.png', reading: 'È arrivato il momento di mettere ordine. Una questione rimandata, una mail ignorata o una responsabilità lasciata sul pianerottolo chiede finalmente di essere affrontata. Purtroppo sei tu quello con le chiavi.' },
  { slug: 'il-regolamento-condominiale', roman: 'V', title: 'Il regolamento condominiale', image: 'il-regolamento-condominiale.png', reading: 'Oggi incontrerai un confine. Prima di superarlo, assicurati almeno di sapere chi lo ha tracciato e perché. Le regole più interessanti sono quelle che nessuno ricorda di aver approvato.' },
  { slug: 'gli-amanti', roman: 'VI', title: 'Gli amanti', image: 'gli-amanti.png', reading: 'Una piccola alleanza può rendere la giornata sorprendentemente più semplice. Non serve innamorarsi: a volte basta qualcuno che tenga aperta la porta mentre hai entrambe le mani occupate.' },
  { slug: 'il-trasloco', roman: 'VII', title: 'Il trasloco', image: 'il-trasloco.png', reading: 'Qualcosa deve cambiare posto. Potrebbe essere una cosa importante o semplicemente quella sedia che da sei mesi impedisce di aprire bene una porta. Fare spazio è comunque una forma di movimento.' },
  { slug: 'la-sopportazione', roman: 'VIII', title: 'La sopportazione', image: 'la-sopportazione.png', reading: 'La vera prova di forza di oggi sarà non reagire. A una porta sbattuta, a un trapano prematuro, a qualcosa lasciato dove non dovrebbe essere. Non tutto ciò che irrita merita una guerra condominiale.' },
  { slug: 'il-vicino-fantasma', roman: 'IX', title: 'Il vicino fantasma', image: 'il-vicino-fantasma.png', reading: 'Oggi potresti avere bisogno di scomparire per un po’. Nessun incontro sulle scale, nessuna conversazione davanti all’ascensore, nessuna spiegazione. Essere irreperibili ogni tanto è una legittima forma di manutenzione.' },
  { slug: 'l-ascensore', roman: 'X', title: 'L’ascensore', image: 'l-ascensore.png', reading: 'Qualcosa si muove, ma non tutto dipende da te. Puoi scegliere il piano, raramente chi salirà durante il tragitto. Accetta qualche incontro imprevisto: dura comunque meno di quanto sembra.' },
  { slug: 'l-assemblea', roman: 'XI', title: 'L’assemblea', image: 'l-assemblea.png', reading: 'È il giorno delle opinioni. Tutti ne avranno una e almeno due saranno incompatibili. Prima di aggiungere la tua, chiediti se vuoi davvero partecipare alla discussione o soltanto uscirne vincitore.' },
  { slug: 'l-appeso', roman: 'XII', title: 'L’appeso', image: 'l-appeso.png', reading: 'Per una volta, lascia qualcosa sospeso. Una risposta, una decisione, una maglietta ancora umida. Non tutto migliora intervenendo immediatamente: alcune cose hanno semplicemente bisogno di stare lì ad asciugare.' },
  { slug: 'il-canbio-di-inquilino', roman: 'XIII', title: 'Il cambio di inquilino', image: 'il-canbio-di-inquilino.png', reading: 'Qualcosa finisce per fare posto a qualcos’altro. Le stanze cambiano persone, gli oggetti cambiano proprietario, certe abitudini spariscono senza cerimonie. Non trattenere ciò che ha già consegnato le chiavi.' },
  { slug: 'l-ora-di-silenzio', roman: 'XIV', title: 'L’ora di silenzio', image: 'l-ora-di-silenzio.png', reading: 'Abbassa il volume. Non soltanto quello della musica. Oggi c’è qualcosa che puoi capire soltanto smettendo per un momento di aggiungere rumore.' },
  { slug: 'le-spese-condominiali', roman: 'XV', title: 'Le spese condominiali', image: 'le-spese-condominiali.png', reading: 'Quello che condividiamo prima o poi presenta un conto. Potrebbe essere denaro, tempo oppure l’ennesimo favore che eri sicuro sarebbe rimasto “una cosa veloce”. Oggi controlla bene le quote.' },
  { slug: 'la-bolletta', roman: 'XVI', title: 'La bolletta', image: 'la-bolletta.png', reading: 'Una realtà che avresti preferito ignorare sta per diventare molto difficile da ignorare. Arriverà con numeri precisi e poche possibilità di interpretazione. Apri la busta: l’ansia raramente applica tariffe migliori.' },
  { slug: 'la-luce-a-tempo', roman: 'XVII', title: 'La luce a tempo', image: 'la-luce-a-tempo.png', reading: 'Hai una finestra breve, ma sufficiente. Se c’è qualcosa da fare, fallo prima che la luce delle scale si spenga e tu debba cercare il pulsante al buio. Non tutte le occasioni devono durare molto per essere utili.' },
  { slug: 'i-rumori-notturni', roman: 'XVIII', title: 'I rumori notturni', image: 'i-rumori-notturni.png', reading: 'Non tutto ciò che senti ha una spiegazione immediata. Un colpo, dei passi, qualcosa che striscia al piano di sopra. Prima di costruire una teoria completa, considera l’ipotesi meno interessante. Spesso è quella giusta.' },
  { slug: 'il-gatto', roman: 'XIX', title: 'Il gatto', image: 'il-gatto.png', reading: 'Oggi prendi esempio da chi occupa il pianerottolo come se gli appartenesse da sempre. Cerca il punto caldo, sistemati comodo e smetti di chiederti continuamente se stai disturbando qualcuno.' },
  { slug: 'la-pace', roman: 'XX', title: 'La pace', image: 'la-pace.png', reading: 'Una piccola guerra può finalmente finire. Non perché qualcuno avesse ragione, ma perché a un certo punto continuare diventa più faticoso che salutarsi di nuovo. Una tregua conta comunque come progresso.' },
  { slug: 'il-condominio', roman: 'XXI', title: 'Il condominio', image: 'il-condominio.png', reading: 'Per quanto tu possa chiudere bene la porta, fai parte di qualcosa che continua oltre il tuo appartamento. Rumori, odori, favori, fastidi, presenze. Oggi ricordati che vivere insieme è soprattutto questo: essere inevitabilmente parte della vita degli altri.' },
]);

export function jannelTarotAsset(card) {
  return `${baseUrl}assets/tarot/${card.image}`;
}
