export const neighborProfiles = {
  fantasma: { title: 'Il Fantasma', shareImage: 'assets/quiz/share/il-fantasma.png', vector: { social: -9, ordine: 0, regole: -2, rumore: -7, curiosita: -6, possesso: -3 }, description: "Abiti qui? Difficile dirlo. Entri, esci, paghi l'affitto e possibilmente non lasci tracce. I vicini potrebbero incontrarti sulle scale da mesi senza sapere esattamente chi tu sia. Il tuo sogno è un appartamento con ingresso indipendente, ascensore privato e nessun gruppo WhatsApp." },
  impiccione: { title: "L'Impiccione", shareImage: 'assets/quiz/share/l-impiccione.png', vector: { social: 3, ordine: 0, regole: 1, rumore: -1, curiosita: 10, possesso: 0 }, description: "Non vuoi sapere tutto. Ti capita semplicemente di sapere tutto. Riconosci i rumori degli appartamenti, conosci gli orari dei vicini e sai quando qualcuno ha ricevuto un pacco ancora prima che lo apra. Non è curiosità. È attenzione all'ambiente. Almeno, così la chiami." },
  proprietario: { title: 'Il Proprietario Morale', shareImage: 'assets/quiz/share/il-proprietario-morale.png', vector: { social: -1, ordine: 7, regole: 10, rumore: -6, curiosita: 4, possesso: 2 }, description: "Non sei il proprietario dell'appartamento. Ma del condominio, moralmente, sì. Conosci le regole, sai cosa si può fare e cosa no e hai un'opinione molto precisa sull'utilizzo degli spazi comuni. Non vuoi essere rompiscatole. Vuoi soltanto che le cose vengano fatte come si deve." },
  sociale: { title: "L'Iper-sociale", shareImage: 'assets/quiz/share/l-iper-sociale.png', vector: { social: 10, ordine: 0, regole: 0, rumore: 3, curiosita: 4, possesso: 1 }, description: "Per te un condominio non è un edificio: è una community. Conosci i vicini, saluti tutti, fai due chiacchiere in ascensore e probabilmente hai già invitato qualcuno a prendere un caffè. Se qualcuno organizza una cena condominiale, probabilmente sei tu." },
  minimalista: { title: 'Il Minimalista Accidentale', shareImage: 'assets/quiz/share/il-minimalista-accidentale.png', vector: { social: -1, ordine: 3, regole: -1, rumore: -2, curiosita: -1, possesso: -10 }, description: "Non hai scelto una vita minimalista. È semplicemente successo. Hai pochi mobili, pochi oggetti e almeno tre cose che continui a rimandare perché 'tanto prima o poi mi trasferisco'. La tua casa non è vuota: è in fase di allestimento dal 2022." },
  rumoroso: { title: 'Il Rumoroso', shareImage: 'assets/quiz/share/il-rumoroso.png', vector: { social: 3, ordine: -2, regole: -7, rumore: 10, curiosita: 1, possesso: 2 }, description: "La casa per te è un luogo da vivere, non da attraversare in punta di piedi. Ascolti musica, cucini, aspiri, trascini sedie, chiudi porte e occasionalmente fai un buco nel muro. Non lo fai apposta. Semplicemente dimentichi che le pareti non sono insonorizzate." },
  incasinato: { title: "L'Incasinato", shareImage: 'assets/quiz/share/l-incasinato.png', vector: { social: 1, ordine: -10, regole: -3, rumore: 2, curiosita: 0, possesso: 5 }, description: "La tua casa segue una logica precisa. Il problema è che la logica la conosci soltanto tu. Hai una sedia per i vestiti, una superficie per le cose 'da sistemare', almeno un cassetto di oggetti misteriosi e probabilmente sai esattamente dove trovare qualcosa... dopo aver cercato per venti minuti." },
  ordine: { title: "Il Maniaco dell'Ordine", shareImage: 'assets/quiz/share/il-maniaco-dell-ordine.png', vector: { social: -1, ordine: 10, regole: 6, rumore: -4, curiosita: 1, possesso: -2 }, description: "Per te una cosa non è semplicemente 'a posto'. È nel posto giusto. Sai dove si trova ogni oggetto, hai probabilmente sviluppato una relazione personale con i prodotti per la pulizia e non riesci a rilassarti se c'è una cosa fuori posto." },
};

const a = (text, values) => ({ text, values });
export const neighborQuestions = [
  { question: 'Hai appena fatto la spesa. Cosa succede alle buste?', answers: [a('Sistemo tutto immediatamente.', { ordine: 3, possesso: 1 }), a('Appoggio tutto da qualche parte e poi me ne dimentico.', { ordine: -3, possesso: 2 }), a('Finisco per offrire qualcosa a chi è in casa.', { social: 3, possesso: 1 }), a('Mi accorgo che ho comprato pochissime cose.', { possesso: -3, social: -1 })] },
  { question: 'Sono le 23:30 e senti rumori dal piano di sopra.', answers: [a('Mi chiedo immediatamente cosa stiano facendo.', { curiosita: 4 }), a('Alzo il volume della mia musica.', { rumore: 4, regole: -2 }), a('Non mi interessa minimamente.', { curiosita: -4, social: -2 }), a('Controllo se è un orario consentito.', { regole: 4, ordine: 1 })] },
  { question: 'Trovi una cosa lasciata sul pianerottolo.', answers: [a('Mi chiedo subito di chi sia.', { curiosita: 4 }), a('Non me ne accorgo nemmeno.', { curiosita: -3, social: -2 }), a('Mi dà fastidio che sia nello spazio comune.', { regole: 4, ordine: 2 }), a('La sposto e continuo per la mia strada.', { regole: -1, social: -1 })] },
  { question: 'Hai invitato otto persone a casa.', answers: [a('Avviso i vicini per educazione.', { social: 2, regole: 3 }), a('Non avviso nessuno.', { social: -2, regole: -3 }), a('Alla fine della serata conosco anche mezzo palazzo.', { social: 5, curiosita: 2 }), a('Mi accorgo che otto persone sono troppe quando sono già arrivate.', { ordine: -3, social: 2 })] },
  { question: 'Hai una cosa rotta in casa.', answers: [a('La aggiusto immediatamente.', { ordine: 3, regole: 1 }), a("La lascio lì finché non diventa parte dell'arredamento.", { ordine: -4 }), a('La sostituisco con qualcosa che avevo già.', { possesso: -2 }), a('La aggiusto con nastro adesivo e buona volontà.', { ordine: -1, possesso: 2 })] },
  { question: 'Quanto può durare una pila di vestiti sulla sedia?', answers: [a('Non esiste una pila di vestiti sulla mia sedia.', { ordine: 5 }), a('Finché non mi serve la sedia.', { ordine: -3 }), a('Ormai quella è ufficialmente la sedia dei vestiti.', { ordine: -5, possesso: 2 }), a('Li tengo pochi: li lavo e li rimetto via.', { ordine: 2, possesso: -2 })] },
  { question: 'Il vicino parcheggia male, ma non occupa il tuo posto.', answers: [a('Non è un mio problema.', { regole: -3, curiosita: -1 }), a('Lo noto comunque.', { curiosita: 2, ordine: 2 }), a('Mi chiedo perché lo faccia e da quanto tempo.', { curiosita: 5 }), a('Prima o poi qualcuno dovrà dirglielo.', { regole: 5 })] },
  { question: 'Il gruppo WhatsApp del condominio si anima alle 7:15.', answers: [a('Silenzio assoluto. Non sono affari miei.', { social: -3, curiosita: -3 }), a('Apro immediatamente.', { curiosita: 5 }), a('Leggo tutto ma non intervengo mai.', { curiosita: 2, social: -2 }), a('Se riguarda una regola, intervengo.', { regole: 5 })] },
  { question: 'Hai un pomeriggio completamente libero.', answers: [a('Finalmente posso sistemare casa.', { ordine: 5 }), a('Finalmente posso non parlare con nessuno.', { social: -5 }), a('Invito qualcuno.', { social: 5 }), a('Faccio musica, cucino, pulisco: vediamo cosa succede.', { rumore: 4, social: 2 })] },
  { question: 'Il vicino ti ferma sulle scale e inizia a raccontarti una cosa.', answers: [a('Mi fermo volentieri a parlare.', { social: 5 }), a('Cerco di capire cosa sta succedendo nella sua vita.', { curiosita: 5 }), a('Sorrido, saluto e continuo.', { social: -2 }), a('Finisco per spiegargli anche cosa prevede il regolamento.', { regole: 4, curiosita: 2 })] },
  { question: 'Ti accorgi che nel bagno hai pochissime cose.', answers: [a('Perfetto. È tutto quello che mi serve.', { possesso: -5 }), a('Devo assolutamente comprare altra roba.', { possesso: 4 }), a('Non so nemmeno cosa ci sia nei miei cassetti.', { ordine: -3, possesso: 3 }), a('Ogni cosa ha il suo posto preciso.', { ordine: 5, possesso: -1 })] },
  { question: 'Sono le 8:01. Devi fare un buco nel muro.', answers: [a('Lo faccio. È un orario normale.', { rumore: 4, regole: -2 }), a('Aspetto. Non vorrei disturbare.', { rumore: -3, regole: 2 }), a('Controllo prima gli orari consentiti.', { regole: 5 }), a('Lo faccio e vediamo chi si lamenta.', { rumore: 5, regole: -4 })] },
  { question: "Trovi una bicicletta lasciata da settimane nell'androne.", answers: [a('Mi chiedo immediatamente di chi sia.', { curiosita: 5 }), a('Non mi ero mai accorto che fosse lì.', { curiosita: -4 }), a('Prima o poi qualcuno dovrà occuparsene.', { regole: 4 }), a('Se nessuno la usa, potrei anche usarla io.', { regole: -2, possesso: -2 })] },
  { question: 'Hai appena pulito casa.', answers: [a("Adesso non sopporto l'idea che qualcuno sporchi.", { ordine: 5 }), a('È durata pulita circa quattro minuti.', { ordine: -5 }), a('Adesso posso finalmente invitare qualcuno.', { social: 4 }), a('Ho spostato talmente tante cose che non so più dove siano.', { ordine: -3, possesso: 2 })] },
  { question: 'Arriva un nuovo vicino.', answers: [a('So già chi è prima ancora che si presenti.', { curiosita: 6 }), a('Lo saluto e mi presento.', { social: 5 }), a('Aspetto che si presenti lui.', { social: -2 }), a('Probabilmente non mi accorgerò nemmeno che è arrivato.', { social: -4, curiosita: -3 })] },
  { question: 'Il vicino mette musica alle 21:30.', answers: [a('Non mi dà fastidio.', { rumore: 2, regole: -1 }), a('Mi chiedo subito quanto durerà.', { curiosita: 3 }), a("Dipende dal volume. C'è un regolamento.", { regole: 5 }), a('Alzo anche la mia.', { rumore: 5, regole: -3 })] },
  { question: 'Quanto spesso parli con i tuoi vicini?', answers: [a('Praticamente mai.', { social: -6 }), a('Solo quando capita.', { social: -1 }), a('Spesso. Con alcuni siamo amici.', { social: 5 }), a('Conosco praticamente tutti quelli del palazzo.', { social: 6, curiosita: 3 })] },
  { question: 'Hai un cassetto pieno di oggetti che non usi.', answers: [a('Non esiste. Periodicamente butto tutto.', { ordine: 3, possesso: -5 }), a("Ne ho uno. So anche esattamente cosa c'è dentro.", { ordine: 4, possesso: 2 }), a('Ne ho almeno tre e non so cosa contengano.', { ordine: -5, possesso: 5 }), a('Non ho praticamente niente da metterci.', { possesso: -6 })] },
  { question: 'Quale frase ti rappresenta di più?', answers: [a('“Non voglio disturbare nessuno.”', { social: -2, rumore: -4 }), a('“Ma chi è quello che abita al quinto?”', { curiosita: 5, social: 2 }), a('“Questa cosa non si può fare.”', { regole: 6 }), a('“Dove l’ho messo?”', { ordine: -5 })] },
];
