const freezeArticle = (article) => Object.freeze({
  ...article,
  paragraphs: Object.freeze(article.paragraphs),
});

export const elevatorArticle = freezeArticle({
  id: 'elevator-science',
  kicker: 'QUIZ DA ASCENSORE',
  title: 'La scienza del posto giusto',
  deck: 'La prossemica studia il modo in cui usiamo lo spazio tra noi e gli altri. L’ascensore è uno dei suoi laboratori più scomodi.',
  paragraphs: [
    'Esistono delle regole non scritte che le persone sembrano applicare senza che siano mai state spiegate a nessuno. Bastano pochi secondi in un ascensore condiviso per vederle in azione.',
    'La prima è la **gestione del perimetro vitale**: si cerca sempre il punto più lontano possibile da chiunque altro. L’antropologo Edward Hall, che nel 1963 ha fondato lo studio della prossemica, ha misurato quanto spazio pretendiamo attorno al corpo a seconda di chi abbiamo davanti — pochi centimetri per un partner, oltre un metro per un conoscente. Un ascensore condominiale medio misura poco più di un metro per lato, il che costringe due vicini di casa, che dovrebbero stare a distanza “sociale”, dentro un perimetro da distanza “intima”. La reazione è una disposizione geometrica metodica con una sola regola: mettersi sempre nell’angolo più lontano disponibile.',
    'La seconda regola riguarda chi entra e chi esce: prima escono le persone dentro, poi entrano quelle fuori, mai il contrario — la stessa regola vale per negozi e mezzi pubblici. Tra chi deve entrare, la precedenza va tradizionalmente a chi viene considerato più fragile: le persone anziane prima dei più giovani, chi porta pacchi ingombranti, chi è visibilmente in difficoltà. Non è una legge, ma è una convenzione che quasi tutti rispettano senza doverla imparare da nessuna parte. Chi entra per primo tende a scegliere l’angolo vicino alla porta o alla parete, chi entra dopo si dispone in diagonale rispetto a chi c’è già; mai e poi mai allinearsi in linea retta: due persone affiancate manderebbero il bizzarro segnale di una misteriosa complicità di coppia che nessuno vuole millantare.',
    'La terza è lo sguardo, ed è la più delicata: va usato, ma con misura. Il sociologo Erving Goffman l’ha chiamata disattenzione civile: un micro-secondo di contatto visivo all’ingresso per certificare l’esistenza reciproca (“Sì, ti ho visto, siamo vivi”), seguito dall’immediata deviazione degli occhi verso il soffitto, le scarpe o il display dei piani. Un esperimento condotto proprio in ascensore, negli anni Ottanta, ha misurato cosa succede a violare quella misura in entrambe le direzioni: chi fissava troppo a lungo generava disagio nell’altro passeggero, ma lo stesso disagio si presentava in chi evitava lo sguardo in modo troppo plateale, per l’intero tragitto.',
    'L’ultima regola è come si esce: scattare verso le porte prima che si aprano è da maleducati impazienti, ma restare impalati fino all’ultimo sentendosi addosso gli occhi inquisitori di chi rimane è pure peggio. La mossa maestra? Attendere che il battente si spalanchi e scivolare via rapidi nella scia del primo che osa muoversi.',
  ],
});

export const homeArticle = freezeArticle({
  id: 'what-makes-a-home',
  kicker: 'ARTICOLO',
  title: 'Cosa rende una casa Casa?',
  deck: 'La casa è un magazzino, un rifugio, una memoria. Ma quando smette di essere soltanto un edificio?',
  paragraphs: [
    'Vi siete mai chiesti cosa renda casa vostra “Casa”? Sono i coinquilini molesti, la vostra tazza preferita, l’aroma inconfondibile di soffritto che aleggia nell’ingresso? O forse sono i ricordi, o l’abitudine? E ancora, la risposta è sempre stata la stessa per tutti?',
    'Non lo è mai stata. Bisogna tornare alla preistoria per trovare il punto esatto in cui la casa nasce, e la prima risposta a questa domanda non aveva niente a che fare con il calore degli affetti, il design d’interni o le foto ricordo. Aveva a che fare con il grano.',
    'Prima della rivoluzione agricola, il problema non si poneva proprio: i cacciatori-raccoglitori inseguivano la cena per le praterie e il concetto di “tetto” coincideva con qualsiasi anfratto in cui capitava di crollare dal sonno la sera. Il cambiamento arriva quando un gruppo umano ha smesso di rincorrere le calorie e ha iniziato a coltivarle, restando fermo sullo stesso pezzo di terra per generazioni. Un raccolto, a differenza di una preda inseguita e mangiata subito, va conservato: servono granai, ripostigli, un tetto sotto cui tenere gli attrezzi al riparo dalla pioggia. La casa nasce, letteralmente, come magazzino. Prima ancora di essere il posto dove si vive, è il posto dove si mette qualcosa da parte per il momento in cui servirà.',
    'Le prime capanne neolitiche erano assimilabili agli appartamenti di alcuni fuorisede a Milano: una sola stanza, spesso di pianta circolare, costruita con pali di legno e frasche intrecciate. Al centro, o vicino alla soglia, un focolare — l’unico punto fisso attorno a cui si organizzava tutto il resto: si dormiva vicino, si mangiava vicino, ci si scaldava vicino. La parola stessa che oggi usiamo, casa, arriva dal latino e in origine significava proprio capanna: il riparo più elementare che un gruppo di persone potesse mettersi sopra la testa.',
    'Da lì in avanti, però, la domanda con cui siamo partiti — cosa rende una casa Casa — ha continuato a cambiare risposta a ogni epoca.',
    'Per un romano, la risposta non aveva niente a che fare con l’intimità. Ogni casa patrizia custodiva un larario, un piccolo altare — spesso proprio nell’atrio, il punto più visibile della domus — dove ardeva un fuoco che non doveva mai spegnersi, in onore dei Lari: gli spiriti degli antenati, ritenuti ancora presenti, convinti che fosse loro dovere ficcare il naso negli affari dei discendenti. Prima di ogni pasto, uno schiavo portava un’offerta di cibo al larario e la gettava nel fuoco; solo quando tornava dicendo che gli dei avevano gradito, la famiglia poteva sedersi a tavola. Era una relazione dare-avere quotidiana: io proteggo il fuoco, il fuoco protegge me. Ciò che rendeva accogliente una casa antica era la rassicurante certezza di non essere mai e poi mai, da soli: i fantasmi dei trisavoli erano lì, vigili e pronti a essere consultati ogni volta che si varcava la soglia.',
    'Per i greci, avere una casa non serviva a ritirarsi dal mondo. Serviva a poterne fare parte: senza una casa, un cittadino non aveva un luogo che fosse davvero suo, e quindi non aveva le basi materiali per partecipare alla vita della città. La casa non era il rifugio dal mondo, ma il requisito necessario per farne parte. La parola stessa da cui deriva “privacy”, privatus, in latino significava letteralmente deprivato: essere confinato alla sfera privata voleva dire essere escluso dalla vita pubblica, una condizione negativa, quasi una punizione. Quello che oggi difendiamo come un diritto sacro, duemila anni fa era considerato una punizione.',
    'Nel Medioevo la sostanza non cambia molto, anche se cambia il nome: “privato” diventa sinonimo di “familiare”, ma dentro quella famiglia non c’era spazio per il singolo. Si dormiva tutti nello stesso letto, si mangiava nella stessa scodella e spesso non ci si disturbava nemmeno a usare nomi propri, bastava un soprannome. La casa restava, psicologicamente, un corpo collettivo, non il luogo dove una persona si definiva come individuo.',
    'La vera rivoluzione arriva con la nascita dell’intimità: il momento storico in cui qualcuno ha finalmente pensato “Sapete che c’è? Vorrei non vedere le vostre facce per cinque minuti”. Gli storici del diritto collocano questo passaggio nella dissoluzione della società feudale e nell’ascesa della borghesia: la possibilità di ritagliarsi uno spazio privato diventa un modo per la nuova classe emergente di distinguersi da chi uno spazio privato non poteva permetterselo. La stanza singola, il letto a uso esclusivo e i pensieri non condivisi vengono percepiti come un costosissimo capriccio per ricchi, non come un bisogno innato. Da lì la strada verso oggi è quasi lineare: nell’Ottocento la sfera privata comincia a essere trattata come diritto della persona, e nel 1890 due avvocati americani, Samuel Warren e Louis Brandeis, scrivono il primo vero trattato giuridico sul “right to privacy” — mossi, pare, da un fatto personale: la moglie di uno dei due era stata fotografata a una festa privata, e la foto era finita su un giornale contro la volontà della famiglia. Da lì in avanti, la privacy smette per sempre di essere una mancanza. Diventa qualcosa da difendere per legge.',
    'In circa duemilacinquecento anni, insomma, il significato psicologico dell’abitare si è capovolto quasi esattamente al contrario: la casa antica funzionava attraverso la presenza costantementre la casa moderna funziona attraverso l’assenza, la possibilità di chiudere una porta e restare, finalmente, soli.',
    'Ed è proprio dentro quella conquista moderna della solitudine che si può rispondere, oggi, alla domanda iniziale: cosa rende un edificio casa. Nel 1988 lo psicologo dei consumi Russell Belk ha pubblicato uno studio che sostiene una tesi che i nostri averi non sono solo cose che possediamo, ma estensioni di chi siamo. È il motivo per cui, per esempio, quando qualcuno subisce un furto in casa riporta dopo l’irruzione, meno senso di comunità, meno percezione di privacy, meno orgoglio per l’aspetto della propria abitazione, anche quando il danno materiale sottratto è minimo. Non fa male l’oggetto rubato in sé, ma il pezzo di identità che quella cosa custodiva.',
    'Il motivo, secondo Belk, è che un oggetto conta raramente per quello che è in sé. Conta per la relazione che porta con sé — quello che lui chiama un legame “persona-oggetto-persona”: chi lo ha regalato, chi lo usava prima, quale momento della vita rappresenta. Un oggetto economico e insignificante per chiunque altro può pesare, nel rendere una stanza casa, molto più di un mobile costoso ma anonimo.',
    'Il secondo ingrediente è il tempo. La psicologia ambientale lo chiama attaccamento al luogo: un legame che si costruisce tra una persona e uno spazio fisico con il tempo. È per questo che una casa nuova, anche bellissima, non sembra casa il primo giorno: mancano disastri quotidiani, risate, caffè rovesciati e domeniche pigre, che trasformano uno spazio in un rifugio.',
    'Tirando le somme, la magia di casa nostra ha pochissimo a che fare con i muri portanti: è la somma dei pezzi di relazioni e memoria incastonati negli oggetti che ci stanno dentro, e del tempo ripetuto passato a costruirli, due cose che non si possono ordinare online con consegna rapida. E due cose, va detto, che non sarebbero state comprensibili per un romano.',
  ],
});

export const intercomArticle = freezeArticle({
  id: 'intercom-history',
  kicker: 'STORIA DEL CITOFONO',
  title: 'Aprite quella porta!',
  deck: 'Breve storia di come l’umanità ha imparato a non urlare per strada',
  paragraphs: [
    'Immaginate di essere un corriere. Avete in mano un pacco e un indirizzo: quarto piano, interno 12, signora Rossi. Siete davanti al portone di un condominio qualunque, uno dei tanti palazzi anni Sessanta con la facciata color crema che punteggiano ogni città italiana. C’è solo un piccolissimo dettaglio: quel palazzo non ha il citofono. Non è fuori uso, non si è staccata l’etichetta: non esiste proprio. Avete un cognome, un piano, un numero di interno, e nessun modo per far arrivare quell’informazione a più di venti metri di altezza attraverso un muro portante. Potete bussare al portone, ma il portone non porta a nessun appartamento in particolare: porta a tutti e a nessuno contemporaneamente. Potete urlare “Rossi!” verso le finestre, pregando che la diretta interessata si affacci prima che qualche vicino esasperato vi lanci una secchiata d’acqua. Potete aspettare che qualcuno esca o entri e infilarvi nella scia, ma a quel punto siete dentro un androne buio, davanti a una fila di porte identiche, senza sapere quale sia la 12.',
    'È il genere di paralisi logistica che oggi risolviamo senza pensarci, con un dito su un pulsante. Ma il problema che quel citofono risolve, mettere in comunicazione un punto preciso all’esterno con un punto preciso, verticale, invisibile all’interno è una rogna antica rimasta irrisolta per secoli.',
    'Per secoli, chi abitava in un condominio aveva a disposizione essenzialmente due strategie, e nessuna delle due prevedeva l’idea di raggiungere qualcuno in particolare. La prima era il portone lasciato aperto: entra chi vuole, sale chi gli pare, e la sicurezza del palazzo è interamente affidata alla fatica di fare le scale, la seconda era il portiere, un instancabile essere umano piazzato all’ingresso il cui unico compito era fare da filtro, da centralino vivente e da memoria di chi abitava dove. Non esisteva una via di mezzo. O il palazzo si fidava di chiunque bussasse, o si fidava di una persona sola che doveva sapere tutto di tutti.',
    'Il portiere, in questo schema era l’unica tecnologia disponibile. Sapeva riconoscere le voci, ricordava i nomi, decideva chi far salire e chi tenere in strada.',
    'Le prime soluzioni “ingegneristiche”, quando finalmente videro la luce, non erano altro che un modo per allungare le corde vocali del custode: nei primi del Novecento comparvero nei palazzi più signorili dei condotti scavati nei muri, tubi di pietra o metallo che convogliavano il suono da un’imboccatura vicino al portone fino a un punto interno, dove di solito c’era proprio la portineria. Non si parlava con l’appartamento: si parlava ancora, semplicemente in modo più comodo, con il portiere.',
    'L’idea di spedire la voce dentro un tubo, in realtà, vanta nobili origini. Nel Codice Atlantico, tra uno schizzo bellico e l’altro, persino Leonardo da Vinci si era inventato un sistema di condotti in rame per far chiacchierare le sentinelle tra due torri di una fortezza, con tanto di rudimentali trombe acustiche alle estremità per coprire chilometri di distanza. Non sappiamo se l’abbia mai collaudato davvero, ma la fisica di base, la voce che viaggia meglio dentro un tubo chiuso che all’aria aperta, è la stessa identica intuizione che, quattrocento anni dopo, si è fatta largo tra le pareti dei palazzi borghesi.',
    'Il salto vero, che ha mandato il portiere in pensione arriva con l’elettricità. Il campanello elettrico, diffuso nelle case italiane a partire dai primi decenni del Novecento, sembra un progresso banale: un pulsante, un filo, un suono, eppure ha rischiato di sovvertire equilibri sociali secolari: prima di allora, chi rincasava a notte fonda senza custode doveva prendere a pugni il portone o sgolarsi dal marciapiede, beccandosi all’istante l’etichetta di poco di buono da tutto il vicinato svegliato nel cuore della notte, ora invece poteva rintanarsi sotto le coperte con discrezione.',
    'Da lì la strada verso il citofono vero e proprio, quello che permette non solo di aprire ma di sentire chi sta suonando, fu una questione di decenni: nei condomini italiani più comuni, quelli senza pretese signorili, il citofono si diffonde su larga scala solo nel secondo dopoguerra, quando il “parla e ascolta” installato nel muro dell’appartamento comincia a sostituire, edificio per edificio, la figura del portiere-centralino. Il videocitofono, che aggiunge un occhio a quell’orecchio meccanico, arriverà solo molto più tardi.',
    'Nel frattempo, prima di tutti questi prodigi elettrici, per far viaggiare non la voce ma la materia dal quarto piano alla strada si usava una trovata infinitamente più poetica ed ecologica: il caro, vecchio “panaro”, il cesto calato con la corda dal balcone. Serviva per tirare su il pane, certo, ma anche per i salvataggi d’emergenza: bastava calarlo per recuperare al volo le chiavi di casa dimenticate, risparmiandosi una scalata infinita fino all’ultimo piano, oppure per invitare l’amico di sotto ad aprirsi la porta da solo.',
  ],
});
